### PR TITLE
Fix getting the Azure public IP address in the publicipaddress actuator

### LINKED ISSUE #35: If the public IP address for a service is deleted, the new public IP address created by the CCM gets deleted by the remedy controller
**What happened**:
If the Azure public IP address for a Kubernetes service is deleted without deleting the service first (e.g. manually), the Azure CCM would, when it next reconciles the service, create a new Azure public IP address with exactly the same name as before, since the name is based on the service UID, but with a different IP. This triggers a reconciliation by the remedy controller and it tries to delete the "old" public IP address by its name. However, since the old and the new public IP addresses actually have the same name, the new IP address is deleted.

**What you expected to happen**:
The remedy controller should recognise that the Azure public IP address with the name saved in the status of the `publicipaddress` resource now has a new IP address than the one that should be deleted, and not try to delete it at all.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a test service of type `LoadBalancer`, and wait until it has been reconciled by the CCM and the remedy controller. 
2. Manually delete the Azure public IP address object. You would need to delete its load balancing rules and its frontend IP configuration from the Azure load balancer object first.
3. Restart CCM so that it reconciles the service again.
4. After CCM has reconciled the service, the remedy controller will kick-in and delete the Azure public IP address object once again. In the logs you could see something similar to:

```
{"level":"info","ts":"2020-12-08T02:33:18.934Z","logger":"azureservice-load-balancer-ips-changed-predicate","msg":"Updating service LoadBalancer IPs"}
{"level":"info","ts":"2020-12-08T02:33:18.934Z","logger":"azureservice-controller","msg":"Reconciling object creation or update","kind":"/v1, Kind=Service","name":"istio-ingressgateway","namespace":"istio-system"}
{"level":"info","ts":"2020-12-08T02:33:18.934Z","logger":"azureservice-actuator","msg":"Creating or updating publicipaddress","name":"istio-system-istio-ingressgateway-20.73.194.245","namespace":"shoot--kyma--c-8af2f07"}
{"level":"info","ts":"2020-12-08T02:33:18.953Z","logger":"azureservice-actuator","msg":"Deleting publicipaddress","name":"istio-system-istio-ingressgateway-20.73.200.162","namespace":"shoot--kyma--c-8af2f07"}
...
{"level":"info","ts":"2020-12-08T02:38:20.896Z","logger":"azurepublicipaddress-actuator","msg":"Removing Azure public IP address from the load balancer","id":"/subscriptions/cbb146b1-eca1-4cfa-81ae-8b80a770f23f/resourceGroups/shoot--kyma--c-8af2f07/providers/Microsoft.Network/publicIPAddresses/shoot--kyma--c-8af2f07-ad468ddba99d3470998a988e70bc899c"}
{"level":"info","ts":"2020-12-08T02:38:21.876Z","logger":"azurepublicipaddress-actuator","msg":"Deleting Azure public IP address","name":"c"}
...
```

**Anything else we need to know**:
The root cause for the issue is that the code that finds an Azure public IP address corresponding to a `publicipaddress` resource searches by `status.name` if it's not empty, or by `spec.ipAddress` otherwise. This is problematic, because:
* If the Azure public IP address at `status.name` has a new IP address, as above, it may find the wrong object.
* If the Azure public IP address with `spec.ipAddress` does not belong to the correct service, again it may find the wrong object.

Therefore:
* An Azure public IP address found by name should only be considered a match if its IP address matches `spec.ipAddress` as well.
* An Azure public IP address found by IP should only be considered a match if its `service` tag matches the service of the `publicipaddress`.

/platform azure
/priority critical

### PR DESCRIPTION
**Pull request by stoyanr**
**What this PR does / why we need it**:
Fixes getting the Azure public IP address in the `publicipaddress` actuator to avoid the issues described in #35.

**Which issue(s) this PR fixes**:
Fixes #35

**Special notes for your reviewer**:

**Release note**:
```improvement operator
Fixed a bug that caused the public IP address created by the CCM to be deleted by the remedy controller in some circumstances.
```

### CODE REVIEW

File: pkg/controller/azure/publicipaddress/actuator.go [hunk 1]
```diff
@@ -279,7 +300,14 @@ func getFailedOperations(pubip *azurev1alpha1.PublicIPAddress) []azurev1alpha1.F
 }
 
 func shouldNotClean(pubip *azurev1alpha1.PublicIPAddress) bool {
-	return pubip.Annotations[DoNotCleanAnnotation] == strconv.FormatBool(true)
+	return pubip.Annotations[controllerazure.DoNotCleanAnnotation] == strconv.FormatBool(true)
+}
+
+func getServiceName(pubip *azurev1alpha1.PublicIPAddress) string {
```
Comment (dkistner) [inline pkg/controller/azure/publicipaddress/actuator.go:306]: Just a minor thing. Not better to return here a `*string`? Then we could later check for `serviceName != nil` instead of `serviceName == ""`.

**Review by dkistner — APPROVED** [review]
Nice PR. 
Just an optional nit.

File: pkg/controller/azure/publicipaddress/actuator.go (hunk 1 above)
Comment (stoyanr) [reply pkg/controller/azure/publicipaddress/actuator.go:306]: @dkistner I can change it if you insist, but from my perspective it doesn't make much difference. `getServiceName` will never return an empty string if the pubip is associated with a service (an empty string is not a valid service name), so an empty string rather than a nil pointer should be perfectly ok here.

Comment (dkistner) [reply pkg/controller/azure/publicipaddress/actuator.go:306]: As said just a nit. Up to you :)
