### PR TITLE
Enhance handling of finalizers by the generic reconciler

### LINKED ISSUE #24: Starting the remedy controller after a service type changed doesn't cause the corresponding objects to be deleted and the finalizer removed
**What happened**:
Starting the remedy controller after a service type changed to `ClusterIP` doesn't cause its corresponding `publicipaddress` objects to be deleted and the finalizer removed from the service.

**What you expected to happen**:
Starting the remedy controller after a service type changed to `ClusterIP` should cause its corresponding `publicipaddress` objects to be deleted and the finalizer removed from the service.

**How to reproduce it (as minimally and precisely as possible)**:
* Start the remedy controller.
* Create a service of type `LoadBalancer` and check that the `publicipaddress` object for the service has been created and the finalizer was added.
* Stop the remedy controller.
* Change the service type from `LoadBalancer` to `ClusterIP`.
* Start the remedy controller. The `publicipaddress` object for the service and the finalizer are still there.

**Anything else we need to know**:
This behavior is caused by the service predicate filtering `Create` events only for services that have load balancer IPs. When the service controller is restarted, it could receive `Create` events for all existing services, but since services without load balancer IPs are filtered out, it won't receive events for services that changed their type while the controller was down.

To fix this, the service predicate should not filter any `Create` events. However, with the current reconciler implementation this would lead to a finalizer being added (and then removed) to all services, including those of type `ClusterIP`. This is undesirable, since it would affect a much bigger number of services and might interfere with normal operation.

Therefore, the reconciler behavior should be changed as well. Instead of always adding the finalizer when creating or updating an object, it should ask the actuator if the object "should be finalized":
* If yes, it should ensure the finalizer and ask the actuator to reconcile. 
* If not and the object already has a finalizer, it should ask the actuator to reconcile and then remove the finalizer.
* If not and the object doesn't have a finalizer, it should not ask the actuator to reconcile (no-op).

### PR DESCRIPTION
**Pull request by stoyanr**
**What this PR does / why we need it**:
* Changes the service predicate to not filter any `Create` events. 
* Changes the `Actuator` interface and the `Reconciler` behavior as described in #24.

**Which issue(s) this PR fixes**:
Fixes #24

**Special notes for your reviewer**:

**Release note**:
```improvement operator
NONE
```

### CODE REVIEW

File: pkg/controller/azure/service/actuator.go [hunk 1]
```diff
@@ -77,43 +73,56 @@ func (a *actuator) CreateOrUpdate(ctx context.Context, obj runtime.Object) (requ
...
 
 	// Delete PublicIPAddress objects for non-existing LoadBalancer IPs
 	pubipList := &azurev1alpha1.PublicIPAddressList{}
 	if err := a.client.List(ctx, pubipList, client.InNamespace(a.namespace), client.MatchingLabels(pubipLabels)); err != nil {
-		return 0, false, errors.Wrap(err, "could not list publicipaddresses")
+		return 0, errors.Wrap(err, "could not list publicipaddresses")
 	}
 	for _, pubip := range pubipList.Items {
-		if _, ok := ips[pubip.Spec.IPAddress]; !ok {
+		if _, ok := ips[pubip.Spec.IPAddress]; !ok || shouldIgnore {
```
Comment (Gchbg) [inline pkg/controller/azure/service/actuator.go:108]: I don't understand the logic here. If the service has the annotation (shouldIgnore) then the pubip will get an annotation but then be immediately deleted. That seems redundant.

Comment (stoyanr) [reply pkg/controller/azure/service/actuator.go:108]: It's not redundant, in fact it's essential. Unless the annotation is there, the public IP address in Azure will get cleaned up, and this is not what you want. You want the pubip to get deleted without any impact on Azure, and therefore it has to be annotated with the "do-not-clean" annotation before that.

File: pkg/controller/azure/service/actuator.go [hunk 2]
```diff
@@ -145,34 +154,33 @@ func (a *actuator) Delete(ctx context.Context, obj runtime.Object) error {
...
+		return false, errors.New("reconciled object is not a service")
+	}
+
+	// Return true if there are LoadBalancer IPs and the service should not be ignored
+	return len(getServiceLoadBalancerIPs(svc)) > 0 && !shouldIgnoreService(svc), nil
+}
+
 func getServiceLoadBalancerIPs(svc *corev1.Service) map[string]bool {
 	ips := make(map[string]bool)
-	if svc.Spec.Type == corev1.ServiceTypeLoadBalancer {
```
[the remark this answers is not in the document]
Comment (stoyanr) [reply pkg/controller/azure/service/actuator.go:150]: It's not entirely wrong, but it's redundant. You are interested in the load balancer IPs, not in whether the service is of type "load balancer" or not. The real impact of the change is when the controller becomes aware of the change in the service type:
* without the change, it sees LoadBalancer -> ClusterIP immediately (before the IP is released), but ClusterIP -> LoadBalancer with a delay (only after the IP is allocated).
* with the change, it sees both changes with a delay (only after the IP is released / allocated).
I prefer the second since it's a bit more consistent and easier to reason about.
